server:
  port: ${currency-service.port:8085}
spring:
  data:
    mongodb:
      host: "${mongodb.host:localhost}"
      port: ${mongodb.port:27017}
converter:
  scale: ${currency-service.converter.scale:4}